homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://10.0.0.11:1883'
  user: loxberry
  password: cxvkjbsvdkjvd
serial:
  port: /dev/ttyACM0
advanced:
  log_directory: data/log/
  log_file: log.txt
  channel: 11
  network_key:
    - 78
    - 206
    - 209
    - 152
    - 138
    - 194
    - 188
    - 206
    - 74
    - 180
    - 80
    - 78
    - 223
    - 249
    - 132
    - 202
  elapsed: false
  last_seen: ISO_8601
devices: devices.yaml
groups: groups.yaml
frontend:
  port: 8078
experimental:
  new_api: true

